// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import UsersFilterController from "./users_filter_controller"
application.register("users-filter", UsersFilterController)
