version: '3.9'

services:
  web:
    build: .
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  sidekiq:
    build: .
    command: bash -c "bundle exec rails db:prepare && bundle exec sidekiq"
    depends_on:
      - db
      - redis
      - mailcatcher
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1026:1025"

  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: